apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-data
  namespace: radio
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
