#!/usr/bin/env bats
# Tests for the ffconcat playlist invariants.
# The playlist is generated by both job-bootstrap.yaml and job-sync.yaml.
# The bug that muted the stream: wrong first line or absolute paths in file entries.
#
# This test exercises the shell snippet that builds the playlist (extracted
# verbatim from the k8s manifests) and asserts all invariants.

setup() {
  WORK=$(mktemp -d)
  mkdir -p "$WORK/music/active"

  # Fake some mp3 files
  touch "$WORK/music/active/track-01.mp3"
  touch "$WORK/music/active/track-02.mp3"
  touch "$WORK/music/active/track-03.mp3"

  PLAYLIST="$WORK/playlist.txt"

  # Reproduce the exact shell snippet from job-sync.yaml / job-bootstrap.yaml
  # (working directory is $WORK so that glob produces relative paths)
  (
    cd "$WORK"
    {
      echo "ffconcat version 1.0"
      for f in music/active/*.mp3; do echo "file '$f'"; done
      echo "file 'playlist.txt'"
    } > "$PLAYLIST"
  )
}

teardown() {
  rm -rf "$WORK"
}

@test "first line is exactly 'ffconcat version 1.0'" {
  first=$(head -1 "$PLAYLIST")
  [ "$first" = "ffconcat version 1.0" ]
}

@test "last line is exactly \"file 'playlist.txt'\" (self-reference)" {
  last=$(tail -1 "$PLAYLIST")
  [ "$last" = "file 'playlist.txt'" ]
}

@test "all file entries use relative paths (no leading /)" {
  # Skip first (header) and last (self-ref) lines; check file lines
  grep "^file " "$PLAYLIST" | head -n -1 | while IFS= read -r line; do
    # Extract the path between single quotes
    path=${line#file \'}
    path=${path%\'}
    case "$path" in
      /*)
        echo "Absolute path found: $path" >&2
        return 1
        ;;
    esac
  done
}

@test "all three mp3 tracks appear in the playlist" {
  grep -q "track-01.mp3" "$PLAYLIST"
  grep -q "track-02.mp3" "$PLAYLIST"
  grep -q "track-03.mp3" "$PLAYLIST"
}

@test "playlist has the correct number of lines (header + N tracks + self-ref)" {
  n_tracks=3
  expected=$(( n_tracks + 2 ))   # header + tracks + self-ref
  actual=$(wc -l < "$PLAYLIST")
  [ "$actual" -eq "$expected" ]
}

@test "no blank lines in playlist" {
  count=$(grep -c '^$' "$PLAYLIST" || true)
  [ "$count" -eq 0 ]
}

@test "empty music/active dir produces header + self-ref only (no glob literal)" {
  WORK2=$(mktemp -d)
  mkdir -p "$WORK2/music/active"   # empty directory
  PLAYLIST2="$WORK2/playlist.txt"
  (
    cd "$WORK2"
    {
      echo "ffconcat version 1.0"
      for f in music/active/*.mp3; do
        # POSIX: if glob matches nothing, $f is the literal pattern
        [ -e "$f" ] && echo "file '$f'"
      done
      echo "file 'playlist.txt'"
    } > "$PLAYLIST2"
  )
  first=$(head -1 "$PLAYLIST2")
  last=$(tail -1 "$PLAYLIST2")
  lines=$(wc -l < "$PLAYLIST2")
  [ "$first" = "ffconcat version 1.0" ]
  [ "$last" = "file 'playlist.txt'" ]
  [ "$lines" -eq 2 ]
  rm -rf "$WORK2"
}
